Allow SelfSignedCertificates already provisioned
port-labs/helm-charts pull request #104
Opened 2024-05-14 12:19 UTC by driosalido

# Description

What - Allow SelfSignedCertificates already provisioned as secrets
Why - 
How -

## Type of change

Please leave one option from the following and delete the rest:

- [X] New feature (non-breaking change which adds functionality)

2024-05-15 10:57 UTC, stavbernazport commented on charts/port-ocean/values.yaml
> +  key: crt
Just a minor issue over here

```suggestion
  secret: ""
    # name: ""
    # key: crt
```

2024-05-15 10:57 UTC, stavbernazport requested changes
Just a minor values issue, WDYT?

2024-05-16 08:54 UTC, driosalido commented
> Just a minor values issue, WDYT?

I've just committed more changes that address the issue and another changed needed in the certificate secret

2024-05-16 18:31 UTC, yairsimantov20 approved these changes
🌊

2024-05-19 07:11 UTC, stavbernazport approved these changes

2024-05-19 07:12 UTC, merged